### PR TITLE
Revise message

### PR DESCRIPTION
**Pull request by mhaidarhanif**
Revise message

If valid, show 'Yes, input is valid'
If invalid, show 'Sorry, input is invalid'

```js
if (result === true) {
    output.setAttribute('class', 'valid')
    output.innerHTML = 'Yes, input is valid'
} else {
    output.setAttribute('class', 'invalid')
    output.innerHTML = 'Sorry, input is invalid'
}
```

### CODE REVIEW

**Comment by mhaidarhanif** [comment]
@BaraLimbong @ajinbramantio @saktyd @jobegood49 @mariorizki @mfahrianda

**Comment by BaraLimbong** [comment]
test

**Comment by mariorizki** [comment]
Halooooo

**Comment by ajinbramantio** [comment]
cobacoba.com

**Comment by saktyd** [comment]
mantaabs

**Comment by mariorizki** [comment]
cendol gan

**Comment by hexmf** [comment]
i will review this

**Comment by mariorizki** [comment]
bar

**Comment by mariorizki** [comment]
bar @BaraLimbong ?

**Pull request merged**
